# Generated by Django 2.0.2 on 2018-05-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WelearnApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_exam', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePic', models.ImageField(upload_to='uplode')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='TopicExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_exam', models.TextField(default='')),
                ('detail_exam', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='comment_exam',
            name='comment_exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WelearnApp.TopicExam'),
        ),
    ]
