# Generated by Django 2.0.1 on 2018-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelearnApp', '0002_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
