# Generated by Django 2.0.1 on 2018-03-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WelearnApp', '0003_item_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='post_text',
        ),
    ]
