# Generated by Django 2.0.1 on 2018-03-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelearnApp', '0004_auto_20180318_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
